"""Add jellyfin users table

Revision ID: 0a3e7b842ee6
Revises: 
Create Date: 2025-02-07 09:38:13.279235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3e7b842ee6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jellyfin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('is_administrator', sa.Boolean(), nullable=False),
    sa.Column('primary_image_tag', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jellyfin_id')
    )
    op.create_table('tmdb_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jellyseerr_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'AVAILABLE', 'DECLINED', 'DELETED', name='requeststatus'), nullable=False),
    sa.Column('requester', sa.String(length=100), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tmdb_media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jellyseerr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_requests')
    op.drop_table('tmdb_media')
    op.drop_table('jellyfin_users')
    # ### end Alembic commands ###
