"""Rename jellyfin watch history table

Revision ID: 23ad11f4a0fa
Revises: 7d03ce32f7e8
Create Date: 2025-02-07 10:51:13.323800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23ad11f4a0fa'
down_revision: Union[str, None] = '7d03ce32f7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=50), nullable=True),
    sa.Column('played_percentage', sa.Float(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('last_played_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_played', sa.Boolean(), nullable=False),
    sa.Column('runtime_ticks', sa.BigInteger(), nullable=True),
    sa.Column('production_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tmdb_media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['jellyfin_users.jellyfin_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jellyfin_watch_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jellyfin_watch_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imdb_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('played_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('play_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_played_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_played', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('runtime_ticks', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('production_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tmdb_media.id'], name='jellyfin_watch_history_tmdb_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['jellyfin_users.jellyfin_id'], name='jellyfin_watch_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jellyfin_watch_history_pkey')
    )
    op.drop_table('watch_history')
    # ### end Alembic commands ###
