"""Edit jellyfin watch history table

Revision ID: 7d03ce32f7e8
Revises: 7bf9bb5f6c06
Create Date: 2025-02-07 10:49:27.693538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d03ce32f7e8'
down_revision: Union[str, None] = '7bf9bb5f6c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jellyfin_watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=50), nullable=True),
    sa.Column('played_percentage', sa.Float(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('last_played_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_played', sa.Boolean(), nullable=False),
    sa.Column('runtime_ticks', sa.BigInteger(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('production_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tmdb_id'], ['tmdb_media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['jellyfin_users.jellyfin_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jellyfin_watch_history')
    # ### end Alembic commands ###
