"""Add constraint on jellyfin watch history table

Revision ID: a7b0dbbb14ee
Revises: 23ad11f4a0fa
Create Date: 2025-02-07 12:19:38.218903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b0dbbb14ee'
down_revision: Union[str, None] = '23ad11f4a0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_item', 'watch_history', ['user_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_item', 'watch_history', type_='unique')
    # ### end Alembic commands ###
